apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: httpd
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
  - name: httpd
    port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
